Team-momo-front/momo-front

- package.json
- src/components/SearchBar/SearchBar.tsx
- src/components/SearchBar/Select.tsx
- yarn.lock
- close #9 
- 게시물 검색창 UI 구현
- react-icons 의존성 추가
> [Feat] 게시물 검색창 UI 구현

- src/components/Input.tsx
- src/components/Join/JoinForm.tsx
- src/components/Join/validation.ts
- src/components/types/types.ts
- close #15 
- 회원가입 유효성 검사
- 이메일 : 단순 형식 검사
- 비밀번호: 8~16자, 영문 대소문자, 숫자, 특수문자 중 1개 포함, 공백 허용하지 않음
- 닉네임 : 2~10자, 한글, 영문, 숫자 허용, 특수문자 불허
- 전화번호 : 단순 형식 검사(xxx-xxxx-xxxx)
- 모든 폼 작성 완료 & 유효성 검사 결과 오류가 없을 시 '다음으로 넘어가기' 버튼 활성화 되도록 UI 수정
입력 전
입력 후
유효성 검사 시 오류 메세지 이벤트를 onChange로 해서 바로바로 확인할 수 있게 하는게 좋을지
onBlur로 처리해서 focusout시에만 확인할 수 있는게 좋을지 고민되네요.
일단은 onChange로 처리했습니다.
> [Feat] 회원가입 유효성 검사 구현

- src/components/FormField.tsx
- src/components/modals/KakaoMapModal.tsx
- src/pages/CreatePostPage.tsx
- src/utils/getLocalDateTime.ts
- close #38 
- 글 제목, 모임날짜, 글 내용에 제한을 설정합니다.
- 장소 검색 시 "내 위치" 버튼을 제공합니다.
> ✨ Feat: 게시글 생성 페이지 추가기능 구현

- src/pages/DetailPage.tsx
**PR 제목은 다음과 같이 작성하세요!** <br>
[타입] PR 내용 #이슈번호 <br>
ex) [Feat] 썸네일 업로드 기능 구현 #123
- close #58 
- 게시글 작성자인지 여부 및 신청 상태에 따라 적절한 버튼 보여주기
> ✨ Feat: 상세페이지 버튼 상태별 구현

- src/components/Header/Header.tsx
- src/mocks/notifications.ts
- src/types/Notification.ts
- close #63 
- 알림이 있을 경우 헤더의 종 아이콘에 빨간점 표시
- 알림 확인할 수 있는 툴팁 추가
- mock data 추가
> [Feat] 알림 구현

- package.json
- yarn.lock
- close #66 
서버 요청 관련 라이브러리를 설치했습니다
> ➕ [Chore] Axios, React Query 설치

- tailwind.config.js
- close #68 68 
- btn-primary 기본 컬러와 hover 컬러가 같아 hover 효과가 보이지 않음
- 버튼들의 기본 색상을 연한 컬러로 변경
- hover 효과와 명확히 구분되도록 스타일 조정
- 사용자 인터페이스 개선
- 
https://github.com/user-attachments/assets/38cdf910-fac5-40eb-898e-9952828d062c
> 🛠 [Refactor] btn-primary 컬러 변경

- src/pages/CreatePostPage.tsx
- src/pages/CreateProfilePage.tsx
- src/pages/DetailPage.tsx
- src/pages/JoinPage.tsx
- src/pages/ListPage.tsx
- src/pages/LoginPage.tsx
- src/pages/ResetPasswordPage.tsx
- src/pages/ViewParticipantPage.tsx
- src/router/Router.tsx
- close #70 
- 모집글 조회페이지, 모집글 상세페이지, 모집글 생성페이지에 Layout 사용하기
- 불필요한 fragment 삭제
> [Refactor] Layout 사용하기

- src/hooks/useCreatePostForm.ts
- src/pages/CreatePostPage.tsx
- src/types/Post.ts
- close #74 
- 게시물 생성 페이지 데이터 타입을 API명세에 맞게 수정합니다
- field명 수정
- locationId, latitude, longitude 추가
> 🏷️ Fix: 게시물 생성 request 데이터 타입 수정

- src/components/SearchBar/SearchBar.tsx
- src/pages/ListPage.tsx
- src/types/Post.ts
- close #86 
- 빌드중 발생한 타입오류를 해결합니다.
> 🐛 Fix: 타입오류 수정

- src/api/axiosInstance.ts
- src/api/meeting.ts
- src/hooks/useCreateMeeting.ts
- src/router/Router.tsx
- close #80 
- baseUrl 지정한 공통 axiosInstance 설정
- react query를 이용하기 위한 QueryClientProvider 추가
- useMutation을 이용한 POST 요청 훅 구현
- 게시물 생성 API 호출 훅 구현
access token이 있어야 호출이 가능해서 API 테스트는 차후 진행예정입니다.
> ✨ Feat: 게시물 생성 api 호출 훅

- src/components/modals/KakaoMapModal.tsx
- src/hooks/useCreatePostForm.ts
- src/pages/CreatePostPage.tsx
- close #82 
- post 요청할 data의 타입 수정
- useCreatePostForm 리팩토링
> ✨ Feat: 게시글 생성하기

- src/components/Header/Header.tsx
- close #84
- Header컴포넌트에서 map사용시 child에 key props이 없어 콘솔에 경고 찍힘
- key props 추가
> 🐛 Fix: Header - map사용 시 key설정

- eslint.config.js
- src/api/apiClient.ts
- src/api/axiosInstance.ts
- close #89 
- axios interceptor로 Access Token 처리로직을 설정해, 각 호출 함수에서 별도로 처리해야하는 번거로움을 없앴습니다.
- API 요청 로직을 재사용 가능한 함수로 분리했습니다.
- any 타입을 금지하는 esLint 규칙을 비활성화했습니다.
> ✨ Feat: axios interceptor 세팅 및 apiClient 구현

- src/components/Join/JoinForm.tsx
- src/components/Join/VerifyEmailCode.tsx
- src/components/Login/KakaoLogin.tsx
- src/components/Login/LoginForm.tsx
- src/router/Router.tsx
- src/states/recoilState.ts
- vite.config.ts
- close #77 
- 카카오 로그인 기능의 부재
- 카카오 로그인 구현
- accessToken을 전역 변수로 관리하도록 수정
> ✨ [Feat] 카카오 로그인 구현

- src/hooks/useSearchMeetings.ts
- src/pages/ListPage.tsx
- close #98 
- 게시글 조회 API 호출 훅 구현
> ✨ Feat: 게시글 조회하기

- src/hooks/useDeleteMeeting.ts
- src/pages/ViewParticipantPage.tsx
- close #100
- 모집글 삭제하는 API 호출 훅 구현
- 게시글 작성자가 모집취소 버튼을 누르면 "모임을 취소하시겠습니까?" 확인창 띄우기
- 확인을 누르면 Delete 요청
> ✨ Feat: 모집 취소하기

- src/hooks/useSearchMeetings.ts
- src/pages/ListPage.tsx
- close #111 
- 사용자가 로딩, 에러, 게시물 없음 상태를 인지할 수 없음
- 로딩상태 동안 데이터의 undefined 상태 핸들링 미구현
- 지속적으로 서버 호출 발생
- 로딩상태에도 오류 없도록 undefined 핸들링
- 로딩, 에러, 게시물 없음 상태 화면 구현
- 불필요한 refetch 제한
> 🐛 Fix: 게시물 조회 API 상태관리

- package.json
- src/components/MyPage/AccountDeletion.tsx
- yarn.lock
- close #113 
- 회원 탈퇴 기능의 부재
- 회원 탈퇴 호출
> ✨ [Feat] 회원 탈퇴

- src/components/Header/Header.tsx
- src/components/Join/RedirectResetPassword.tsx
- src/components/Join/ResetPassword.tsx
- src/components/Login/KakaoLogin.tsx
- src/components/Login/LoginForm.tsx
- src/router/Router.tsx
- close #117 
- 카카오 로그아웃 / 일반 로그아웃 구분하여 호출
- 카카오 로그아웃 & 일반 로그아웃 통합된 API로 호출
> 🐛 [Fix] 로그아웃 api 주소 수정

- src/components/FormField.tsx
공통범위의 작업인데 브랜치를 실수로 분리해 바로 merge합니다
> ♻️ Refactor: FormField 리팩토링

- src/pages/ApplyMeetingPage.tsx
- src/pages/PostEditPage.tsx
- close #125 
- 유사한 레이아웃의 페이지들의 코드가 각 파일별로 따로 작성되어있음
- #126  의 레이아웃 컴포넌트를 사용
- 게시글 편집 기능 구현
> ♻️ Refactor: 상세페이지에 레이아웃 사용

- src/hooks/useCreatePostForm.ts
오타를 수정합니다
locatinoId -> locationId
> ✏️ Fix: 오기 수정

- src/pages/CreatePostPage.tsx
- close #130 
- 이미지 중앙정렬
- 입력창, 지도 크기 확대
- text area 크기 확대, 크기조절 비활성화
> 💄 Fix: 게시글 생성 페이지 레이아웃 수정

- src/components/Join/CreateProfile.tsx
- src/components/Join/VerifyEmailCode.tsx
- close #135 
- 프로필 생성 완료 후 로그인 하러 가기 모달 활성화
- 이메일 인증 완료 후 로그인 하러 가기 모달 활성화
- 기존의 alert 창 대체
> ♻️ [Refactor] 이메일 인증 완료 후 UI/UX 수정

- src/components/Join/CreateProfile.tsx
- close #145 
- 프로필 생성 리다이렉트 주소가 상대경로로 잘못 설정됨
- 프로필 생성 리다이렉트 주소 절대경로로 수정
> 🐛 [Fix] 프로필 생성 리다이렉트 주소 절대경로로 수정

- src/components/LoadingSpinner.tsx
- src/components/MyPage/AccountDeletion.tsx
- src/components/MyPage/MyProfile.tsx
- src/pages/ListPage.tsx
- close #148 
- 로딩상태에서 보여주는 스피너가 화면마다 상이
- 컴포넌트 사용하도록 통일
> ✨ Feat: 로딩스피너 컴포넌트

- src/components/Login/KakaoLogin.tsx
- src/components/Login/LoginForm.tsx
- close #143 
- 로그인 API 호출시 상태 관리의 부재
- 로그인 API 호출시 로딩 상태 및 에러 처리 개선
> ♻️ [Refactor] 로그인 로딩 상태 및 에러 처리 개선

- src/components/Header/Header.tsx
- src/components/Join/VerifyEmailCode.tsx
- src/components/Login/KakaoLogin.tsx
- src/components/Login/LoginForm.tsx
- close #141 
- 로그아웃 시 로딩 상태 및 에러 처리의 부재
-  로그아웃 시 로딩 상태 및 에러 처리
> ♻️ [Refactor] 로그아웃 로딩 상태 및 에러 처리 개선

- src/components/MyPage/ParticipantList.tsx
- src/hooks/useGetParticipants.ts
- src/types/User.ts
- close #160 
- 신청자 목록 불러오는 API 호출 훅 구현
> ✨ Feat: 신청자 목록 불러오기

- src/hooks/useCloseMeeting.ts
- src/pages/ViewParticipantPage.tsx
> ✨ Feat: 모집완료 기능 구현

- package.json
- src/api/chatrooms.ts
- src/components/Chat/ChatList.tsx
- src/components/Chat/ChatModal.tsx
- src/hooks/useSearchChatRooms.ts
- src/types/Chat.ts
- yarn.lock
- close #167 
- 채팅 목록 조회 API의 부재
- 채팅 목록 조회 API 연동
- apiClient를 사용해 채팅 API 호출 함수 정의
- WebSocket / STOMP 의존성 추가
> ✨ [Feat] Chat 목록 조회 API 연동

- src/components/Login/LoginForm.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/PostCard.tsx
- src/components/PostCardBtn.tsx
- src/pages/ViewParticipantPage.tsx
- src/types/Meeting.ts
- src/types/Post.ts
- close #195 
- 버튼 이벤트의 부재
- 버튼을 클릭하면 이동하게 구현
- query로 상태를 담아 보내서 신청자 페이지 버튼 구현
- PostCard 
> ✨ [Feat] 모집글 보기 & 신청자 보기 버튼

- src/api/paricipations.ts
- src/components/Login/LoginForm.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/PostCard.tsx
- src/components/PostCardBtn.tsx
- src/hooks/useGetMyParticipatedMeetings.ts
- src/pages/PostEditPage.tsx
- src/pages/ViewParticipantPage.tsx
- src/types/Meeting.ts
- src/types/Post.ts
- src/utils/getStatusAndColorByRole.ts
- close #193 
- api 연동의 부재
- 참가한 모임을 서버로부터 받아온다.
- 상태값 서버와 통일
- 공통 함수에 return 반환값 없는 문제 수정 -> 모임 신청 리팩토링 필요
api 수정 후 테스트 필요
> ✨ [Feat] 참가한 모임 조회

- src/api/meeting.ts
- src/api/paricipations.ts
- src/components/Login/LoginForm.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/PostCard.tsx
- src/components/PostCardBtn.tsx
- src/hooks/useGetMyParticipatedMeetings.ts
- src/hooks/useParticipateMeeting.ts
- src/pages/ApplyMeetingPage.tsx
- src/pages/PostEditPage.tsx
- src/pages/ViewParticipantPage.tsx
- src/types/Meeting.ts
- src/types/Post.ts
- src/utils/getStatusAndColorByRole.ts
- close #191 
- 모임 신청 기능의 부재
- 모임 신청 기능 구현
신청자인지 아닌지는 구분하는 값은 신청한 목록 api 호출 후 구현해야 할 것 같습니다.
> ✨ [Feat] 모임 신청 기능 구현

- src/api/meeting.ts
- src/api/paricipations.ts
- src/components/Login/LoginForm.tsx
- src/components/MyPage/HostedMeetings.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/PostCard.tsx
- src/components/PostCardBtn.tsx
- src/hooks/useGetMyParticipatedMeetings.ts
- src/hooks/useGetmyMeetings.ts
- src/hooks/useParticipateMeeting.ts
- src/pages/ApplyMeetingPage.tsx
- src/pages/PostEditPage.tsx
- src/pages/ViewParticipantPage.tsx
- src/types/Meeting.ts
- src/types/Post.ts
- src/utils/convertMeetingsToPosts.ts
- src/utils/getStatusAndColorByRole.ts
- close #189 
- 주최한 목록 페이지 렌더링 오류(타입 불일치)
- 반응형 개선 필요
- 주최한 목록 페이지 렌더링 오류 개선
- 타입 정의 수정
- 반응형 개선 
> ✨ [Feat] 주최한 목록 조회 페이지 개선

- src/hooks/useFetchUserProfile.ts
- close #198 
- select 옵션 사용해 프로필 이미지 선택시 타입 오류 발생
- 타입 오류 수정 
> 🐛 fix: type 오류 수정

- src/components/Chat/ChatFloatingBtn.tsx
- src/components/Chat/ChatModal.tsx
- src/components/Chat/ChatParticipantList.tsx
- src/components/Chat/ChatRoom.tsx
- src/components/Layout/Layout.tsx
- src/hooks/useSearchChatRooms.ts
- src/states/recoilState.ts
- close #202 
- 초기 렌더링시 채팅 버튼 렌더링이 제대로 이루어지지 않음
- 로그인 상태에 따라 채팅 버튼 활성화가 월활하게 이루어지지 않음
- 로그인 상태에 따라 채팅 버튼 렌더링 수정 & 타입 재정의
> ♻️ [Refactor] 채팅 버튼 렌더링 수정

- src/components/MyPage/MyProfile.tsx
- close #204 
- 서버에서 필요한 요청값과 일치하지 않음
- 'request' -> 'updateRequest'로 수정
> 🐛 fix : 프로필 수정 요청값 updateData로 수정

- src/components/MyPage/ParticipantList.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useGetUserProfile.ts
- src/pages/UserProfilePage.tsx
- src/router/Router.tsx
- src/types/User.ts
- close #212 
- 목데이터 렌더링
- 타인 프로필 조회 API 연동
- 렌더링을 위해 roodId 전달하도록 router 설정 추가
profileImage가 반환이 안되고 있습니다.
> ✨ [Feat] 신청자 프로필 보기

- src/api/meeting.ts
- src/api/paricipations.ts
- src/components/DetailPageLayout.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useDeleteParticipation.ts
- src/hooks/useGetMyParticipatedMeetings.ts
- src/hooks/useGetParticipants.ts
- src/hooks/useGetUserProfile.ts
- src/pages/ApplyMeetingPage.tsx
- src/pages/UserProfilePage.tsx
- src/pages/ViewParticipantPage.tsx
- src/router/Router.tsx
- src/types/User.ts
**PR 제목은 다음과 같이 작성하세요!** <br>
[타입] PR 내용 #이슈번호 <br>
ex) [Feat] 썸네일 업로드 기능 구현 #123
- close #207 
- 목데이터용 코드
- API 연동
- UI 개선(버튼 px 카드 요소와 통일, 신청자 리스트 pt 카드 요소와 통일)
> ♻️ [Refactor] 신청자 보기 리팩토링

- src/api/meeting.ts
- src/api/paricipations.ts
- src/components/DetailPageLayout.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useCreatePostForm.ts
- src/hooks/useDeleteParticipation.ts
- src/hooks/useEditMeeting.ts
- src/hooks/useGetMyParticipatedMeetings.ts
- src/hooks/useGetParticipants.ts
- src/hooks/useGetUserProfile.ts
- src/pages/ApplyMeetingPage.tsx
- src/pages/CreatePostPage.tsx
- src/pages/DetailPage.tsx
- src/pages/PostEditPage.tsx
- src/pages/UserProfilePage.tsx
- src/pages/ViewParticipantPage.tsx
- src/router/Router.tsx
- src/types/User.ts
- src/utils/categoryValueToKey.ts
- close #206 
- 썸네일 이미지 파일 업로더 부재
- 수정된 데이터를 JSON 객체로 전달
- 카테고리 값 '한식'과 같이 그대로 전달
- 이미지 파일 업로더 구현
- 수정된 데이터를 formData로 전달
- 카테고리 값을 서버에서 필요한 값으로 변환하는 함수를 유틸 함수로 분리(categoryValueToKey)
> ♻️ [Refactor] 모집글 수정

- package-lock.json
- package.json
- src/components/Header/Header.tsx
- src/hooks/useNotifications.ts
- yarn.lock
- close #216 
- 실시간 알림 기능
- 개별 알림 삭제 기능
- 전체 알림 삭제 기능
> ✨ [Feat] 알림구현

- src/api/paricipations.ts
- src/components/MyPage/ParticipantList.tsx
- src/components/PostCardBtn.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useApproveParticipation.ts
- src/hooks/useCloseMeeting.ts
- src/hooks/useDeleteMeeting.ts
- src/hooks/useRejectParticipation.ts
- src/pages/UserProfilePage.tsx
- src/router/Router.tsx
- src/types/Meeting.ts
- src/types/User.ts
- close #226 
주최자 입장에서 참여 신청자들의 참여 승인 & 거절 구현
> ✨ [Feat] 참여 승인 & 거절

- src/api/chatrooms.ts
- src/components/Chat/ChatList.tsx
- src/components/Chat/ChatModal.tsx
- src/components/Chat/ChatRoom.tsx
- src/components/MyPage/HostedMeetings.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useApproveParticipation.ts
- src/hooks/useDeleteMeeting.ts
- src/hooks/useGetOutChatRoom.ts
- src/hooks/useGetParticipants.ts
- src/hooks/useRejectParticipation.ts
- src/router/Router.tsx
- close #230 
- meetingThumbnail이 null일 때 이미지 테스트값으로 들어감
- 카카오 로그인 유저 초기 닉네임 null
- meetingThumbnail이 null일 때 모집글 생성과 마찬가지로 디폴트 이미지로 들어가도록 수정
- 카카오 로그인 유저 초기 닉네임을 프로필 조회와 마찬가지로 anony + userId이 기본값으로 보이도록 수정
> ♻️ [Refactor] 채팅 기본이미지 설정 및 카카오 유저 닉네임 기본값 설정

- src/components/UserProfileBtn.tsx
- src/hooks/useWithdrawChatParticipant.ts
> ♻️ [Feat] 채팅 참여자 강퇴

- src/hooks/useApproveParticipation.ts
- src/hooks/useDeleteMeeting.ts
- src/hooks/useRejectParticipation.ts
- close #254 
- 오류 객체의 message를 출력
- 오류 객체의 응답값에 데이터 안에 있는 message를 출력 (서버가 가공해서 보내준 text)
> ♻️ [Refactor] 참여 승인/거절 API 오류 핸들링

- src/components/Header/Header.tsx
- close #266 
- 알림목록이 검색창에 가려짐
- 알림목록이 가장 위쪽에 보여지도록 수정
> 🐛 Fix: 알림창 가려짐 수정

- src/api/apiClient.ts
- src/api/uesrs.ts
- src/components/Header/Header.tsx
- src/components/Join/JoinForm.tsx
- src/components/Join/RedirectResetPassword.tsx
- src/components/Join/ResetPassword.tsx
- src/components/Join/VerifyEmailCode.tsx
- src/components/Login/LoginForm.tsx
- src/components/MyPage/AccountDeletion.tsx
- src/components/MyPage/HostedMeetings.tsx
- src/hooks/useDeleteMeeting.ts
- src/hooks/useEditProfile.ts
- src/hooks/useGetUserProfile.ts
- src/hooks/useGetmyMeetings.ts
- src/hooks/useMyProfile.ts
- src/types/User.ts
- close #275 
- 개별 코드로 구현
- 공용 컴포넌트 사용 x
- 프로그램 컨벤션의 통일성 저해
- 공용 컴포넌트를 사용하여 한 곳에서 api 호출 함수를 관리할 수 있도록 개선
- 프로그램의 컨벤션을 통일하여 일관성과 유지 보수성을 높임
> ♻️ [Refactor] users API 공용 컴포넌트로 리팩토링

- src/components/Header/Header.tsx
- close #279 
- 알림 모두 지우기 함수 `deleteAllNotifications` 미호출
-  `() => deleteAllNotifications`에서 `() => deleteAllNotifications()`로 수정 
> 🐛 Fix: 함수 호출하기
