Team-momo-front/momo-front

- src/components/MyPage/HostedMeetings.tsx
- src/components/MyPage/MyMeetings.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/PostCard.tsx
- src/components/PostCardBtn.tsx
- src/mocks/posts.ts
- src/states/recoilState.ts
- src/types/Post.ts
- src/utils/getStatusAndColorByRole.ts
- close #46 
- 카드를 누르면 상세 페이지로 이동
- 참가한 모임 컴포넌트의 부재
- 참가한 모임 컴포넌트 구현
- 현재 활성화 된 역할인 `isActive`상태를 리코일로 정의하여 `isHosted`와 `isParticipated` 값 전역으로 관리
- 해당 값이 있을 경우 카드 눌러도 상세 페이지로 이동 X
- PostCardBtn 컴포넌트 분리
- 상태에 따라 상세페이지 or 관리 페이지 or 삭제할 수 있도록 버튼 구현
- `getStatusAndColorByRole` 함수를 따로 분리하여 상태에 따른 컬러값 할당하여 스타일 유지보수 용이하도록 수정
- 목데이터에 participatedUserId배열과 participationStatus 추가해서 테스트
스크린샷
삭제는 함수만 연결해두었고 API 연동하면서 구현할 예정입니다.
> 🎉 [Feat] 참가한 모임 컴포넌트 구현 및 상태 관리 리팩토링

- src/components/Categories.tsx
- close #51 
- 카테고리를 선택하는 버튼들 모아놓은 컴포넌트
- 조회페이지에서 읽기전용으로 사용하기 위해 수정
> 👔 Refactor: 카테고리버튼 읽기전용 버전 추가

- src/components/Header/Header.tsx
- close #44 
- 비로그인 유저의 헤더만 존재
- 로그인 상태에 따른 헤더 UI 구현
- 프로필 이미지 호버 & 클릭 시 마이페이지, 로그아웃 할 수 있는 드롭다운 생성
https://github.com/user-attachments/assets/2664b641-c72c-44c8-9557-f3af79972a08
> ✨ [Feat] 로그인 유저 헤더 UI 

- src/components/Chat/ChatList.tsx
- src/components/Chat/ChatModal.tsx
- src/components/Chat/ChatParticipantList.tsx
- src/components/Layout/Layout.tsx
- src/components/UserProfileBtn.tsx
- src/pages/CreateProfilePage.tsx
- src/pages/JoinPage.tsx
- src/pages/ListPage.tsx
- src/pages/LoginPage.tsx
- src/pages/MyPage.tsx
- src/pages/ResetPasswordPage.tsx
- src/pages/UserProfilePage.tsx
- src/pages/ViewParticipantPage.tsx
- src/router/Router.tsx
- close #62 
- 공통 Layout 컴포넌트의 부재
- 헤더와 채팅 버튼이 포함된 레이아웃 컴포넌트 구현
- 메인 페이지와 채팅방에서 들어가는 유저 프로필 페이지 제외하고 아울렛 설정
도현님이 작업하신 컴포넌트들 중에서
폴더 구조에서 pages에는 렌더링만 담당하도록 하고 나머지는 컴포넌트로 빼는 작업이 추가로 필요할 것 같습니다.
> ✨ Refactor: Layout 컴포넌트 구현 및 적용

- src/components/Header/Header.tsx
- src/components/Join/VerifyEmailCode.tsx
- src/components/Login/KakaoLogin.tsx
- src/components/Login/LoginForm.tsx
- src/states/recoilState.ts
- src/types/User.ts
- vite.config.ts
- close #95 
- 로그아웃 기능의 부재
- 로그인 유저 타입 분류의 부재
- 전역 변수로 토큰 관리
- 로그인 유저 타입 분류(이메일 로그인 회원/카카오 로그인 회원)
- 로컬 스토리지에 토큰 저장
- 로그 아웃시 로컬 스토리지에서 토큰 및 로그인 유저 타입 삭제
- 로그인 유저 타입에 따라 호출 api 분리해서 호출
- 인증코드 페이지에서 불필요한 onblur 속성 삭제
카카오 로그아웃은 프로필 생성 여부 검증하므로 인터셉터 이용해서 프로필 생성페이지 이동하게 만든 후 다시 로직 검증하겠습니다.
> ✨ [Feat] 로그아웃 구현

- src/hooks/useDebounce.ts
- src/pages/ListPage.tsx
- close #109 
- 카테고리를 선택하고 검색버튼을 눌러야 게시글 목록이 업데이트됨
- 게시글 생성 버튼 클릭시 권한별 동작 미구현
- 카테고리 선택시 게시글 목록 즉시 업데이트
- 과도한 호출을 방지하기 위해 디바운싱 처리
- 로그아웃 상태에서 게시글 생성 버튼 클릭 시 로그인화면으로 유도
> ♻️ Refactor: 메인페이지 리팩토링

- src/components/Join/RedirectResetPassword.tsx
- src/components/Join/ResetPassword.tsx
- src/components/Join/ResetPasswordCallback.tsx
- src/router/Router.tsx
- close #121 
- 비밀번호 재설정 링크 발송 컴포넌트만 존재
- 비밀번호 재설정 콜백 컴포넌트 부재
- 서버 연동 필요
- 비밀번호 재설정 링크 발송 api 연동
- 비밀번호 재설정 api 연동
- 이메일 입력 -> 재설정 링크 전송
- 메일에서 재설정 링크로 ResetPasswordCallback으로 리다이렉트하도록 설정
- 비밀번호 유효성 검증 이후 비밀번호 재설정
후순위로 미룬 작업 : useMutation 사용해서 상태 리팩토링 하려고 합니다.
> ✨ [Feat] 비밀번호 재설정 기능 구현

- src/components/Header/Header.tsx
- src/components/Join/RedirectResetPassword.tsx
- src/components/Join/ResetPassword.tsx
- src/components/Login/KakaoLogin.tsx
- src/components/Login/LoginForm.tsx
- src/components/MyPage/MyProfile.tsx
- src/hooks/useFetchUserProfile.ts
- src/router/Router.tsx
- close #115 
- 프로필 조회 API 호출 실패 시 서버에 API 재호출 함
- 프로필 검증 오류를 나타내는 localstorage에 저장된 hasProfile에 대해 오류 처리 부족
- 프로필 조회 API 호출 실패 시 서버에 API 재호출 하지 않도록 react-query 옵션값 수정
-  프로필 검증 오류를 나타내는 hasProfile === 'false' 에 대한 값을 추가하여 ProfileRedirect 컴포넌트 호출 처리를 분기함
> ♻️ [Refactor] 프로필 조회 API 호출 실패 시 재요청하는 로직 수정

- src/components/DetailPageLayout.tsx
- src/components/FormField.tsx
- src/pages/ApplyMeetingPage.tsx
- src/pages/PostEditPage.tsx
- close #123 
- 상세페이지의 레이아웃이 비슷해 각 파일마다 동일한 코드가 반복됨
- 레이아웃 페이지 구현
- FormField 읽기전용 모드 추가 및 스타일 수정
> ✨ Feat: 상세페이지 레이아웃 컴포넌트 구현

- src/components/Join/RedirectResetPassword.tsx
- src/components/Join/ResetPassword.tsx
- close #147 
- 비밀번호 재설정 링크 발송 시 pending 상태를 나타내는 ui의 부재
- 비밀번호 재설정 링크 발송 시 pending 상태를 나타내도록 버튼 ui 수정
- 비밀번호 재설정 버튼 UI 통일
> ♻️ [Refactor] 비밀번호 재설정 컴포넌트 상태 관리 개선

- src/api/meeting.ts
- src/hooks/useCreatePostForm.ts
- src/pages/CreatePostPage.tsx
- src/types/Meeting.ts
- close #179 
- 썸네일 이미지 형식 제한 X
- thumbnail: string으로 전달. 
- 모집글 생성 기능 요청값이 json 객체
- 썸네일 이미지는 jpg, jpeg, png 형식의 파일만 가능하다.
- thumbnail: string이 아닌 File 형식으로 전달하다.
- 모집글 생성 기능에 전달하는 데이터는 formdata이다.
- isPending으로 데이터 요청 상태를 처리한다.
- thumbnail과 thumbnailUrl을 분리, thumbnail은 File 형식, thumbnailUrl은 미리보기 가능하도록 URL.createObjectURL로 구현
> ♻️ [Refactor] Thumbnail을 파일데이터로 보내도록 모집글 생성시 formdata 전달하도록 수정

- src/api/meeting.ts
- src/api/paricipations.ts
- src/components/DetailPageLayout.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/hooks/useDeleteParticipation.ts
- src/hooks/useGetMyParticipatedMeetings.ts
- src/hooks/useGetParticipants.ts
- src/pages/ApplyMeetingPage.tsx
- src/pages/PostEditPage.tsx
- src/pages/ViewParticipantPage.tsx
- close #210 
- hasApplied 값을 하드코딩하여 신청자 입장 상세페이지 버튼 렌더링 구현(신청 취소 버튼 렌더링 구현x)
- 신청한 모집글 조회 API에서 meetingId 배열을 반환(useQuery의 select 사용)
- 신청한 meetingId에 해당 모집글의 id가 포함되어 있으면 hasApplied를 true로 주어 렌더링 조건으로 사용
- 신청한 모집글은 신청 취소 버튼 렌더링
- 신청 취소 API 연동
> ✨ [Feat] 신청한 모집글 상세 페이지에서 버튼 렌더링 구현(신청자 입장)

- src/hooks/useDeleteParticipation.ts
- src/hooks/useGetMyParticipatedMeetings.ts
- src/hooks/useParticipateMeeting.ts
- src/pages/ApplyMeetingPage.tsx
- src/types/Meeting.ts
- close #214 
- 신청취소 API 참여자 id 전달
- participatingId(신청한 모임의 id)를 계산하는 로직을 추가
- refetch를 활용해 데이터를 다시 불러올 때 hasApplied 상태 변경

> ♻️ [Refactor] 신청 취소 API participationId 값 수정

- src/components/PostCardBtn.tsx
- src/hooks/useCloseMeeting.ts
- src/hooks/useDeleteMeeting.ts
- src/router/Router.tsx
- src/types/Meeting.ts
- close #228 
- 모집 완료 버튼 클릭시 모임 상태 변경 API를 호출하여 "CLOSED" 상태로 변경
- 모임 삭제 API 호출 후 리다이렉트 추가
- 신청자 보기 페이지에서 모집 취소를 누르면 모임이 삭제되고 "마이페이지 - 내 모임"으로 이동
- 모집 완료 후 주최한 모임 목록에서 모임 삭제 버튼을 누르면 모임이 삭제되고 해당 페이지 재마운트
1.
2.
> ✨ [Feat] 모임 삭제 & 모임 상태 변경(모집 완료) 구현

- src/components/MyPage/ParticipantList.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useApproveParticipation.ts
- src/hooks/useGetParticipants.ts
- src/hooks/useRejectParticipation.ts
- src/router/Router.tsx
- close #238 
- 호출 성공 시 단순히 뒤로가기(스택에 남아있어서 앞으로 갈 수 있음)
- 해당 페이지로 리다이렉트 하도록 처리(스택에서 삭제되도록 옵션값 전달)
> ♻️ [Refactor] 참여 승인 / 거절 API 호출 성공 이벤트 처리 개선

- src/components/MyPage/ParticipantList.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useApproveParticipation.ts
- src/hooks/useDeleteMeeting.ts
- src/hooks/useGetParticipants.ts
- src/hooks/useRejectParticipation.ts
- src/router/Router.tsx
- close #236 
- 임의로 라우터에서 컴포넌트에 key값을 주어 모임 취소 API 호출 성공시 임의의 값을 key값으로 갱신하여 해당 컴포넌트가 리렌더링 되도록 함
- tanstackQuery의 invalidateQueries 메서드를 사용하여 캐싱을 무효화하고 주최한 모임 목록 API를 refetch할 수 있도록 리팩토링
> ♻️ [Refactor] 모임 취소 API 호출 성공시 페이지 재렌더링 리팩토링

- src/api/chatrooms.ts
- src/components/Chat/ChatModal.tsx
- src/components/MyPage/HostedMeetings.tsx
- src/components/MyPage/ParticipantList.tsx
- src/components/MyPage/ParticipatedMeetings.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useApproveParticipation.ts
- src/hooks/useDeleteMeeting.ts
- src/hooks/useGetOutChatRoom.ts
- src/hooks/useGetParticipants.ts
- src/hooks/useRejectParticipation.ts
- src/router/Router.tsx
- close #232 
- 채팅 뒤로가기 API 호출의 부재
- 채팅 뒤로가기 API를 통해 채팅 나가기(뒤로가기) 구현
참여자 입장에서 채팅 목록 조회 API의 응답값 중 unreadMessagesCount이 초기화되지 않는 오류가 있어서
추후 백엔드 코드 수정 후 리팩토링 및 테스트 예정입니다.
> ✨ [Feat] 채팅 뒤로가기 구현

- src/hooks/useCreatePostForm.ts
- src/pages/CreatePostPage.tsx
- close #241
- 게시물 생성 시 카테고리를 선택하지 않고 업로드 요청이 허용됨
- 필수입력값인 카테고리가 없는 상태로 API요청이 이루어져 에러 발생
- 카테고리를 선택하지 않은 경우 API요청을 하지 않고 alert 창 띄우기
- 별개로 useEffect의 린트경고무시 주석 추가했습니다
> 🐛 Fix: 카테고리 필수입력 처리

- src/components/Header/Header.tsx
- src/hooks/useFetchUserProfile.ts
- close #243 
- 비로그인 상태에서 useFetchUserProfile 을 호출
- accessToken이 존재할때만 호출 활성화
- 불필요한 refetch 로직 삭제
로딩스피너 컴포넌트로 수정했습니다
> 🐛 Fix: 비로그인시 유저정보 API 호출 비활성화

- src/components/MyPage/MyProfile.tsx
- src/hooks/useEditProfile.ts
- close #247 
- mutation의 데이터 업데이트 로직이 hook마다 상이
- onSuccess 콜백이 hook과 컴포넌트에 따로 존재
- queryClient.invalidateQueries 를 사용해서 데이터를 업데이트하도록 수정
- onSuccess, onError 콜백을 hook에서 관리하도록 수정
- 불필요한 refetch 로직, retry 설정 삭제
- 프로필 성공 알림창 추가
> ♻️ Refactor: useEditProfile 리팩토링

- src/hooks/useDeleteMeeting.ts
- close #256 
- 모집 취소 API 호출 성공 이벤트의 조건으로 설정된 path가 일치하지 않음
- startWith를 사용해서 조건이 제대로 작동하도록 수정
> 🐛 [fix] 모집 취소 API 호출 성공시 리다이렉트 수정

- src/components/Chat/ChatParticipantList.tsx
- src/components/UserProfileBtn.tsx
- src/hooks/useGetChatParticipants.ts
- src/hooks/useWithdrawChatParticipant.ts
- src/pages/UserProfilePage.tsx
- src/types/Chat.ts
- close #251 
- 채팅 참여자 렌더링시 목데이터 사용
- 채팅 참여자 API 호출
- 프로필 페이지로 이동
- 채팅을 통해 유저 프로필 보기로 들어가면 
- 주최자 입장 : 주최자 프로필은 뒤로가기 버튼만, 참여자 프로필은 뒤로가기, 내보내기 버튼 렌더링
- 신청자 입장 : 모든 프로필이 뒤로가기 버튼만 렌더링
> ✨ [Feat] 채팅 참여자 조회

- src/components/PostCardBtn.tsx
- src/hooks/useDeleteMeeting.ts
- src/hooks/useDeleteParticipation.ts
- src/pages/ApplyMeetingPage.tsx
- close #262 
신청한 모집글 모임에서 모집글 카드 삭제 버튼 구현(참여한 모집글 목록에서 제거)
신청자 입장에서 승인 거절, (승인 대기 ->)모집 완료 상태 반환시 삭제 버튼 활성화
신청자 입장에서 승인 거절, (승인 대기 ->)모집 완료 상태 반환시 삭제 버튼 활성화
> ✨ [Feat] 신청한 모임 목록 모집글 카드 삭제 버튼 구현

- src/api/meeting.ts
- src/components/PostCardBtn.tsx
- src/hooks/useCloseMeeting.ts
- src/hooks/useDeleteMeeting.ts
- src/hooks/useDeleteParticipation.ts
- src/pages/ApplyMeetingPage.tsx
- src/types/Meeting.ts
- close #260 
- 모집 상태 변경("모집중", "모집 완료")이 가능
- 참여한 모임 목록에서 승인 대기 중인 회원의 경우 모집 완료 상태가 반환이 되지 않고 계속 승인 대기 상태를 반환함
- "모집중" 상태 변경을 할 필요가 없으므로 모집 완료 API로 변경
- 참여한 모임 목록에서 승인 대기 중인 회원도 모집 완료 상태가 반환되어 삭제 버튼을 활성화 시킬 수 있도록 수정
승인 대기 중 모집 완료된 회원의 카드
승인 완료된 회원의 카드(승인 완료 -> 모임 참여 = 채팅 참여)
> ♻️ [Refactor] 모임 상태 변경 API -> 모집 완료 API로 변경

- src/components/MyPage/HostedMeetings.tsx
- src/hooks/useDeleteMeeting.ts
- src/hooks/useGetmyMeetings.ts
- close #277 
- 채팅 모달에서 모임이 삭제되어도 뒷 화면에 모임 리스트가 업데이트 되지 않음
- 채팅 모달이 활성화 된 페이지 단위로 (업데이트가 필요한 페이지라면) 모임 리스트가 업데이트 되도록 개선
> ♻️ [Refactor] 채팅 모달에서 채팅 삭제 후 모임 리스트 업데이트 개선

- src/api/apiClient.ts
- src/api/getMyProfile.ts
- src/api/uesrs.ts
- src/components/Chat/ChatParticipantList.tsx
- src/components/Chat/ChatRoom.tsx
- src/components/Header/Header.tsx
- src/components/Join/JoinForm.tsx
- src/components/Join/RedirectResetPassword.tsx
- src/components/Join/ResetPassword.tsx
- src/components/Join/VerifyEmailCode.tsx
- src/components/Login/LoginForm.tsx
- src/components/MyPage/AccountDeletion.tsx
- src/components/MyPage/HostedMeetings.tsx
- src/components/MyPage/ParticipantList.tsx
- src/hooks/useDeleteMeeting.ts
- src/hooks/useEditProfile.ts
- src/hooks/useGetUserProfile.ts
- src/hooks/useGetmyMeetings.ts
- src/hooks/useMyProfile.ts
- src/pages/UserProfilePage.tsx
- src/types/User.ts
- close #273 
- 카카오 유저는 기본 닉네임이 없으므로 프론트단에서 기본값을 설정해 보여줌 
- 알림 메세지 등 서버에서 넘어오는 데이터자체에서 닉네임 필드값이 필요한 경우가 있기 때문에 카카오 유저의 경우 백에서 기본값을 설정하고 프론트에 그 값을 내려주는 것으로 변경
- 불필요한 기본값 설정 코드를 제거
> ♻️ [Refactor] 카카오 유저 닉네임 기본값 수정
